// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDJTAGyoNRjPt_gsNyqN2O1iiQZfO8Mtk',
    appId: '1:323283629288:web:1981c8ba40137ca095c55d',
    messagingSenderId: '323283629288',
    projectId: 'ecommerce-c1751',
    authDomain: 'ecommerce-c1751.firebaseapp.com',
    storageBucket: 'ecommerce-c1751.appspot.com',
    measurementId: 'G-2RGX9EQ65E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmegb10cREF7BcHSjBI7HgA0LjaE_yS80',
    appId: '1:323283629288:android:0c09d91534c74e3d95c55d',
    messagingSenderId: '323283629288',
    projectId: 'ecommerce-c1751',
    storageBucket: 'ecommerce-c1751.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxtRIq5lQrGiKSNzDo4hkyZQiz4CkLnxk',
    appId: '1:323283629288:ios:384012037099bfeb95c55d',
    messagingSenderId: '323283629288',
    projectId: 'ecommerce-c1751',
    storageBucket: 'ecommerce-c1751.appspot.com',
    androidClientId: '323283629288-4gi9cl4a18cqt8q1i0cjuqfc10foao0j.apps.googleusercontent.com',
    iosClientId: '323283629288-ti3fijglcr44nrkgudkq3p0js1fi6hjq.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxtRIq5lQrGiKSNzDo4hkyZQiz4CkLnxk',
    appId: '1:323283629288:ios:bc1b49ad0ef4e38495c55d',
    messagingSenderId: '323283629288',
    projectId: 'ecommerce-c1751',
    storageBucket: 'ecommerce-c1751.appspot.com',
    androidClientId: '323283629288-4gi9cl4a18cqt8q1i0cjuqfc10foao0j.apps.googleusercontent.com',
    iosClientId: '323283629288-9m7scgr5s6qvhis9sl4g23hmduqvahru.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApplication.RunnerTests',
  );
}
